name: .NET Core

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Install dependencies
        run: dotnet restore EntityFrameworkCore.Triggered.sln
      - name: Build
        run: dotnet build --configuration Release --no-restore EntityFrameworkCore.Triggered.sln
      - name: Test
        run: dotnet test --no-restore --verbosity normal EntityFrameworkCore.Triggered.sln
  build-samples:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Install dependencies
        run: dotnet restore EntityFrameworkCore.Triggered.Samples.sln
      - name: Build
        run: dotnet build --configuration Release --no-restore  EntityFrameworkCore.Triggered.Samples.sln
